+---
+                                                
+   RosettaCNC QEM Vision Camera Find Markers [arcs, mm]
+   v1.0.2
+   support@rosettacnc.com
+
+   https://docs.vectric.com/docs/V11.0/Aspire/ENU/Help/form/post-processor-editing/index.html
+
+   DESCRIPTION
+   ===========
+   This post is used to create a toolpath which will apply the corrections (rotation/scaling) acquired
+   using the QEM Vision Camera Find Markers tool. 
+   It will require the macro "apply_markers_corrections.ngc" in the machine macros folder.
+--

+---
+   !!! DISCLAIMER !!!
+ 
+   This is a purely demonstrative post-processor, in the "AS IS" form, with no guarantees.
+   This post-processor is provided free of charge by the RosettaCNC Team for Simulator testing only.
+   If you run the G-code generated by this post-processor on a real CNC it is solely your own risk and resonsibility.
+
+   Questo è un post-processore puramente dimostrativo, nella formula "AS IS", senza nessuna garanzia.
+   Questo post-processore è fornito in forma gratuita dal Team di RosettaCNC solo per prove al simulatore.
+   Se eseguite il codice G generato da questo post-processore su una reale CNC è esclusivamente vostro rischio e resonsabilità.
+--

+---
+   Global File Statements
+--
POST_NAME                       = "RosettaCNC QVC Find Markers (arcs, mm)"
FILE_EXTENSION                  = "ngc"
UNITS                           = "MM"
PRINT_DIRECT                    = "NO"
RAPID_PLUNGE_TO_STARTZ          = "NO"
+ DIRECT_OUTPUT                 = "Display Name|Manufacturers.Document"
+ ROTARY_WRAP_Y                 = A
+ ROTARY_WRAP_X                 = B
+ SPINDLE_SPEED_RANGE           = 1 15 4500 15000
+ SUBSTITUTE                    = "O1 S1 O2 S2 On Sn"

+---
+   Tape Splitting Support
+--
+ TAPLE_SPLITTING               = 1000 100 "%s_%s.tap" 1 "YES"

+---
+   Line Terminating Characters                 
+--
LINE_ENDING                     = "[13][10]"

+---
+   Block Numbering                             
+--
LINE_NUMBER_START               = 0
LINE_NUMBER_INCREMENT           = 10
LINE_NUMBER_MAXIMUM             = 999999

+---
+   Variables
+
+   Variable Name               Output Using        Value
+   ============                ============        =====
+   FEED_RATE                   [F]                 Current Feed Rate.
+   CUT_RATE                    [FC]                Current Cut Feed Rate.
+   PLUNGE_RATE                 [FP]                Current Plunge Feed Rate.
+   SPINDLE_SPEED               [S]                 Current Spindle Speed in R.P.M.
+   POWER                       [P]                 Current power setting for jet-based tools (e.g. lasers).
+   TOOL_NUMBER                 [T]                 Current Tool Number.
+   PREVIOUS_TOOL_NUMBER        [TP]                Previous Tool Number.
+   LINE_NUMBER                 [N]                 Line Number.
+   TOOL_NAME                   [TOOLNAME]          Name of Current Tool.
+   TOOL_NOTES                  [TOOL_NOTES]        Text from Note field in ToolDB for current tool.
+   TOOLPATH_NAME               [TOOLPATH_NAME]     Name of Current Toolpath.
+   TOOLPATH_FILENAME           [TP_FILENAME]       Filename (Produced by “Save Toolpath(s)”).
+   TOOLPATH_DIR                [TP_DIR]            Folder Toolpath File was saved to.
+   TOOLPATH_EXTENSION          [TP_EXT]            Toolpath File Extension.
+   TOOLPATH_PATHNAME           [PATHNAME]          Toolpath Folder Pathname.
+   X_POSITION                  [X]                 Current coordinate of tool position in X axis.
+   Y_POSITION                  [Y]                 Current coordinate of tool position in Y axis.
+   Z_POSITION                  [Z]                 Current coordinate of tool position in Z axis.
+   A_POSITION                  [A]                 Current coordinate of tool position in A axis.
+   ARC_CENTRE_I_INC_POSITION   [I]                 Arc centre in X Axis (relative to last X,Y position).
+   ARC_CENTRE_J_INC_POSITION   [J]                 Arc centre in Y Axis (relative to last X,Y position).
+   ARC_CENTRE_I_ABS_POSITION   [IA]                Arc centre in X Axis (absolute coordinates).
+   ARC_CENTRE_J_ABS_POSITION   [JA]                Arc centre in Y Axis (absolute coordinates).
+   ARC_START_X_POSITION        [ArcStartX]         Start position of an arc in X axis.
+   ARC_START_Y_POSITION        [ArcStartY]         Start position of an arc in Y axis.
+   ARC_MID_X_POSITION          [ArcMidX]           Mid-point of arc in X (absolute coordinates).
+   ARC_MID_Y_POSITION          [ArcMidY]           Mid-point of arc in Y (absolute coordinates).
+   ARC_MID_X_INC_POSITION      [ArcMidXI]          Mid-point of arc in X (incremental coordinates).
+   ARC_MID_Y_INC_POSITION      [ArcMidYI]          Mid-point of arc in Y (incremental coordinates).
+   ARC_RADIUS                  [Radius]            The radius of an arc.
+   ARC_ANGLE                   [Angle]             The angle of an arc.
+   X_HOME_POSITION             [XH]                Home tool position for X axis.
+   Y_HOME_POSITION             [YH]                Home tool position for Y axis.
+   Z_HOME_POSITION             [ZH]                Home tool position for Z axis.
+   SAFE_Z_HEIGHT               [SAFEZ]             Safe Z Height / Rapid Clearance Gap.
+   WRAP_DIAMETER               [WRAP_DIA]          Diameter of cylinder that axis is wrapped around.
+   X_LENGTH                    [XLENGTH]           Length of material in X.
+   Y_LENGTH                    [YLENGTH]           Length of material in Y.
+   Z_LENGTH                    [ZLENGTH]           Length of material in Z.
+   X_MIN                       [XMIN]              Minimum value of material in X.
+   Y_MIN                       [YMIN]              Minimum value of material in Y.
+   Z_MIN                       [ZMIN]              Minimum value of material in Z.
+   X_MAX                       [XMAX]              Maximum value of material in X.
+   Y_MAX                       [YMAX]              Maximum value of material in Y.
+   Z_MAX                       [ZMAX]              Maximum value of material in Z.
+   X_ORIGIN_POS                [X_ORIGIN_POS]      Origin Position in X.
+   Y_ORIGIN_POS                [Y_ORIGIN_POS]      Origin Position in Y.
+   Z_ORIGIN                    [Z_ORIGIN]          Z Zero Position, Table or Material Surface.
+   XY_ORIGIN                   [XY_ORIGIN]         X, Y Origin.
+   TOOLS_USED                  [TOOLS_USED]        List of tools used (In order of use).
+   TOOLPATHS_OUTPUT            [TOOLPATHS_OUTPUT]  List of toolpaths used in file (in order of use).
+   TOOLPATH_NOTES              [TOOLPATH_NOTES]    Toolpath Notes (Toolpath Control form).
+   FILE_NOTES                  [FILE_NOTES]        File Notes (Edit > Notes).
+   TIME                        [TIME]              File creation time.
+   DATE                        [DATE]              File creation date.
+   DWELL_TIME                  [DWELL]             Dwell time in seconds when drilling.
+   PRODUCT                     [PRODUCT]           Name of the product used to output file, including version number.
+   TOOL_DIAMETER               [TDIA]              Tool diameter.
+   INVERSE_TIME                [FI]                Rotary: Current Inverse Time Rate
+--

+---
+   Formating for variables                     
+
+   PS: Commented formattings are kept, and represented below, with defaults
+--
VAR LINE_NUMBER                 = [N|A|N|1.0]
VAR SPINDLE_SPEED               = [S|A| S|1.0]
VAR FEED_RATE                   = [F|C| F|1.1]
+ VAR PLUNGE_RATE               = [FP|A||1.0]
+ VAR CUT_RATE                  = [FC|A||1.0]
VAR X_POSITION                  = [X|C| X|1.4]
VAR Y_POSITION                  = [Y|C| Y|1.4]
VAR Z_POSITION                  = [Z|C| Z|1.4]
VAR X_HOME_POSITION             = [XH|A| X|1.4]
VAR Y_HOME_POSITION             = [YH|A| Y|1.4]
VAR Z_HOME_POSITION             = [ZH|A| Z|1.4]
VAR SAFE_Z_HEIGHT               = [SAFEZ|A| Z|1.4]
+ VAR ARC_START_X_POSITION      = [ArcStartX|A||1.3]
+ VAR ARC_START_Y_POSITION      = [ArcStartY|A||1.3]
VAR ARC_CENTRE_I_INC_POSITION   = [I|A| I|1.4]
VAR ARC_CENTRE_J_INC_POSITION   = [J|A| J|1.4]
+ VAR ARC_CENTRE_I_ABS_POSITION = [IA|A||1.3]
+ VAR ARC_CENTRE_J_ABS_POSITION = [JA|A||1.3]
+ VAR ARC_MID_X_POSITION        = [ArcMidX|A||1.3]
+ VAR ARC_MID_Y_POSITION        = [ArcMidY|A||1.3]
+ VAR ARC_MID_X_INC_POSITION    = [ArcMidXI|A||1.3]
+ VAR ARC_MID_Y_INC_POSITION    = [ArcMidYI|A||1.3]
+ VAR ARC_RADIUS                = [Radius|A||1.3]
+ VAR ARC_ANGLE                 = [Angle|A||1.3]
+ VAR X_LENGTH                  = [XLENGTH|A||1.3]
+ VAR Y_LENGTH                  = [XLENGTH|A||1.3]
+ VAR Z_LENGTH                  = [XLENGTH|A||1.3]
+ VAR X_MIN                     = [XMIN|A||1.3]
+ VAR Y_MIN                     = [YMIN|A||1.3]
+ VAR Z_MIN                     = [ZMIN|A||1.3]
+ VAR X_MAX                     = [XMAX|A||1.3]
+ VAR Y_MAX                     = [YMAX|A||1.3]
+ VAR Z_MAX                     = [ZMAX|A||1.3]
VAR DWELL_TIME                  = [DWELL|A| P|1.2]

+---
+   BLOCK: Commands output at the start of the file.
+--
begin HEADER
+"; == BLOCK: HEADER"
"( ==                            == )"
"( ==   Created for RosettaCNC   == )"
"( == from a demo post-processor == )"
"( ==                            == )"
"( ==   QVC Markers Corrections  == )"
"( ==    3 Axis, ATC, Arcs, mm   == )"
"( ==    Mist & Flood Disabled   == )"
"( ==           v1.0.2           == )"
"( ==                            == )"
""
"; DISCLAIMER"
"; =========="
"; This is a purely demonstrative post-processor, in the 'AS IS' form, with no guarantees."
"; This post-processor is provided free of charge by the RosettaCNC Team for simulator testing only."
"; If you run the G-code generated by this post-processor on a real CNC it is solely your own risk and resonsibility."
""
"; [91]VISION_INFO[93]"
";   [FILE_NOTES]"
"; [91]STOCK SIZE[93]"
";   X = [XLENGTH], Y = [YLENGTH], Z =[ZLENGTH]"
"; [91]INITIAL POSITIONS[93]"
";  [XH] (X HOME POSITION)"
";  [YH] (Y HOME POSITION)"
";  [ZH] (Z HOME POSITION)"
";  [SAFEZ] (SAFETY HEIGHT)"
"; [91]USED TOOLS[93]"
";   [TOOLS_USED]"
""
"( PREAMBLE )"
"G17 G21 G40 G49 G50 G67 G69 G80 G90 G91.1 G94"
"G54"
""
"; disable QVC Find Markers acquired corrections"
"G50 G69"
""
"; TOOL: [TOOLNAME]"
"T[T] M06"
"G43 H[T]"
"M03[S]"
""
"; apply QVC Find Markers acquired corrections"
"G65 P[34]apply_markers_corrections[34]"
""
"; TOOLPATH: [TOOLPATH_NAME]"

+---
+   BLOCK: Commands output at toolchange.
+--
begin TOOLCHANGE
""
+"; == BLOCK: TOOLCHANGE"
"; disable QVC Find Markers acquired corrections"
"G50 G69"
""
"; TOOL: [TOOLNAME]"
"T[T] M06"
"G43 H[T]"
""
"; apply QVC Find Markers acquired corrections"
"G65 P[34]apply_markers_corrections[34]"

+---
+   BLOCK: Commands output for a new segment (new toolpath with current toolnumber).
+--
begin NEW_SEGMENT
""
+"; == BLOCK: NEW_SEGMENT"
"; TOOLPATH: [TOOLPATH_NAME]"
"M03[S]"

+---
+   BLOCK: Commands output for Initial rapid move.
+--
begin INITIAL_RAPID_MOVE
+"; == BLOCK: INITIAL_RAPID_MOVE"
"G00[X][Y]"
"G00[ZH]"

+---
+   BLOCK: Commands output for rapid moves.
+--
begin RAPID_MOVE
+"; == BLOCK: RAPID_MOVE"
"G00[X][Y]"
"G00[Z]"

+---
+   BLOCK: Commands output for first feed rate move in a series of feed moves.
+--
begin FIRST_FEED_MOVE
+"; == BLOCK: FIRST_FEED_MOVE"
+@@@"G01[X][Y][Z][F]"
"G01[Z][F]"
"G01[X][Y]"

+---
+   BLOCK: Commands output for feed rate moves.
+--
begin FEED_MOVE
+"; == BLOCK: FEED_MOVE"
"G01[X][Y][Z]"

+---
+   BLOCK: Commands output for the first clockwise arc move in a series of cw arc moves.
+--
begin FIRST_CW_ARC_MOVE
+"; == BLOCK: CW_HELICAL_ARC_PLUNGE_MOVE"
"G02[X][Y][I][J][F]"

+---
+   BLOCK: Commands output for clockwise helical arc plunge move in a series of moves.
+--
begin FIRST_CW_HELICAL_ARC_PLUNGE_MOVE
+"; == BLOCK: CW_HELICAL_ARC_PLUNGE_MOVE"
"G02[X][Y][Z][I][J][F]"

+---
+   BLOCK: Commands output for clockwise helical arc move in a series of moves.
+--
begin FIRST_CW_HELICAL_ARC_MOVE
+"; == BLOCK: FIRST_CW_HELICAL_ARC_MOVE"
"G02[X][Y][Z][I][J][F]"

+---
+   BLOCK: Commands output for clockwise arc moves.
+--
begin CW_ARC_MOVE
+"; == BLOCK: CW_ARC_MOVE"
"G02[X][Y][I][J]"

+---
+   BLOCK: Commands output for clockwise helical arc plunge moves.
+--
begin CW_HELICAL_ARC_PLUNGE_MOVE
+"; == BLOCK: CW_HELICAL_ARC_PLUNGE_MOVE"
"G02[X][Y][Z][I][J]"

+---
+   BLOCK: Commands output for clockwise helical arc moves.
+--
begin CW_HELICAL_ARC_MOVE
+"; == BLOCK: CW_HELICAL_ARC_MOVE"
"G02[X][Y][Z][I][J]"

+---
+   BLOCK: Commands output for the first counter-clockwise arc move in a series of ccw arc moves.
+--
begin FIRST_CCW_ARC_MOVE
+"; == BLOCK: FIRST_CCW_ARC_MOVE"
"G03[X][Y][I][J][F]"

+---
+   BLOCK: Commands output for counter- clockwise helical arc plunge move in a series of moves.
+--
begin FIRST_CCW_HELICAL_ARC_PLUNGE_MOVE
+"; == BLOCK: FIRST_CCW_HELICAL_ARC_PLUNGE_MOVE"
"G03[X][Y][Z][I][J][F]"

+---
+   BLOCK: Commands output for first counter-clockwise helical arc move in a series of moves.
+--
begin FIRST_CCW_HELICAL_ARC_MOVE
+"; == BLOCK: FIRST_CCW_HELICAL_ARC_MOVE"
"G03[X][Y][Z][I][J][F]"

+---
+   BLOCK: Commands output for counter-clockwise arc moves.
+--
begin CCW_ARC_MOVE
+"; == BLOCK: CCW_ARC_MOVE"
"G03[X][Y][I][J]"

+---
+   BLOCK: Commands output for counter clockwise helical arc plunge moves.
+--
begin CCW_HELICAL_ARC_PLUNGE_MOVE
+"; == BLOCK: CCW_HELICAL_ARC_PLUNGE_MOVE"
"G03[X][Y][Z][I][J]"

+---
+   BLOCK: Commands output for counter-clockwise helical arc moves.
+--
begin CCW_HELICAL_ARC_MOVE
+"; == BLOCK: CCW_HELICAL_ARC_MOVE"
"G03[X][Y][Z][I][J]"

+---
+   BLOCK: Commands output at the end of the file.
+--
begin FOOTER
""
+"; == BLOCK: FOOTER"
"( EPILOGUE )"
"M05"
"M09"
""
"; disable QVC Find Markers acquired corrections"
"G50 G69"
""
"M02"

+---
+   BLOCK: 
+--
begin JET_TOOL_POWER
+"; == BLOCK: JET_TOOL_POWER"

+---
+   BLOCK: 
+--
begin JET_TOOL_ON
+"; == BLOCK: JET_TOOL_ON"

+---
+   BLOCK: 
+--
begin JET_TOOL_OFF
+"; == BLOCK: JET_TOOL_OFF"

+---
+   BLOCK: Commands output when feed rate changes.
+--
begin FEED_RATE_CHANGE
+"; == BLOCK: FEED_RATE_CHANGE"

+---
+   BLOCK: Commands output for the First Plunge Move, in a series of plunge moves.
+--
begin FIRST_PLUNGE_MOVE
+"; == BLOCK: FIRST_PLUNGE_MOVE"

+---
+   BLOCK: Commands output for Plunge Moves.
+--
begin PLUNGE_MOVE
+"; == BLOCK: PLUNGE_MOVE"

+---
+   BLOCK: Commands output for Retract Moves.
+--
begin RETRACT_MOVE
+"; == BLOCK: RETRACT_MOVE"
"G00[ZH]"

+---
+   BLOCK: Commands output for a dwell move.
+--
begin DWELL_MOVE
+"; == BLOCK: DWELL_MOVE"
"G04[DWELL]"